### ISSUE TITLE
Curses broken, no normal console interface!

### ISSUE THREAD

**Issue by elspru** [facebookresearch/CommAI-env#33]
Python curses as implemented in this program side scrolls to the left.
it makes it unusable on anything less than a super wide screen,
there is also no history.

Also only one line from teacher is visible, in available examples it seems teacher sometimes is supposed to output more than one line.  Net result is teacher asks things which are impossible to know, like which fruit are ripe in mary's basket, having no previous knowledge of mary's basket. 

Please have the option of a normal console interface (using stdout and stdin) as default. 
Then it would scroll up, like all normal console interfaces, and work on all sizes of console.

**Comment by ajabri** [comment]
Hi @elspru,

Thanks for opening up an issue. We mainly use Linux, and use the human console view when debugging new tasks. There are other views you can use (i.e. PlainView) along with your own learner. If what you want is a vertically growing console, I can see how you might easily implement it -- with the PlainView and your own modified version of HumanLearner. The reason we have it scrolling horizontally is because the construct of segmented tasks is not necessarily intrinsic in the presented problem. 

You might want to try shrinking the size of your text in your terminal if the text is cut off? Please let me know if I am misinterpreting your comments :)

**Comment by elspru** [comment]
how do I enable plainview?
